#!/usr/bin/env bash

if [ "$(whoami)" == "archerd" ]; then
    # background and screensaver/lockscreen
    feh --bg-fill  --randomize /home/archerd/.dotfiles/images/wallpapers/* &
    autorandr -c # force monitor configuration (uses script from feh to resize background)
    #xscreensaver -no-splash &
    xsetroot -cursor_name left_ptr
    # set numlock on by default
    # /usr/bin/numlockx on
    numlockx

    #if type cmus; then
    #    cmus &
    #fi

    /home/archerd/.dotfiles/tray.sh
fi

