#!/bin/bash

if [ "$(whoami)" == "archerd" ]; then
    # background and screensaver/lockscreen
    feh --bg-scale /home/archerd/.dotfiles/wallpaper.png &
    autorandr -c # force monitor configuration (uses script from feh to resize background)
    xscreensaver -no-splash &
    compton &
    xsetroot -cursor_name left_ptr
    # set numlock on by default
    /usr/bin/numlockx on
    # start gnome-pie for graphical menus
    gnome-pie &

    # tray for applets and application notifications
    # trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --widthtype request --transparent true --alpha 63 --tint 0x145A32 --heighttype request --margin 3 --padding 3 &
    # stalonetray --config /home/archerd/.dotfiles/stalonetrayrc &
    trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --widthtype request --transparent true  --padding 3 --iconspacing 2 --heighttype request --tint 0x294029 --alpha 0 &


    # applets (sleep to force desired order)
    xfce4-power-manager &
    sleep 0.010
    nm-applet --sm-disable &
    sleep 0.010
    blueman-applet &
    sleep 0.500
    pasystray &
    sleep 0.400
    redshift-gtk &
    sleep 0.070
    kdeconnect-indicator &
    sleep 0.010

    # software to be autostarted
    if type yubioath-desktop; then
        yubioath-desktop &
    fi
    if type slack; then
        slack --startup --silent &
    fi
    if type background_window; then
        background_window &
    fi
fi

